-- Create analyses table associated with authenticated users
create table if not exists public.analyses (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  link text not null, -- The link provided by the user
  source varchar(50) not null, -- 'twitter', 'reddit', 'linkedin', 'facebook', 'medium', 'other'
  content text not null, -- The scraped page content
  summary text not null, -- Summary generated by Ollama
  perspectives jsonb not null, -- Array of POVs: [{ "name": "...", "stance": "...", "tone": "..." }]
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.analyses enable row level security;

-- RLS Policies: users can only see and insert their own records
create policy "Allow users to read their own analyses" on public.analyses
  for select using (auth.uid() = user_id);

create policy "Allow users to insert their own analyses" on public.analyses
  for insert with check (auth.uid() = user_id);
